---
- name: Playbook for localhost
  hosts: localhost
  connection: local
  gather_facts: yes

  tasks:
    - name: Ensure Nginx is installed
      apt:
        name: nginx
        state: present
      become: yes

    - name: Create a directory
      file:
        path: /tmp/example_directory
        state: directory

    - name: Create a sample file
      copy:
        content: "Hello, Ansible!"
        dest: /tmp/example_directory/hello.txt

    - name: Start Nginx service
      service:
        name: nginx
        state: started
      become: yes
